apiVersion: v1
kind: Service
metadata:
  name: payload-processor
  namespace: ${NAMESPACE}
spec:
  type: NodePort
  selector:
    app: payload-processor
  ports:
    - name: grpc
      port: 9004
      targetPort: 9004
    - name: metrics
      port: 9090
      targetPort: 9090
      nodePort: 30090
